root: true
plugins:
  - prettier
  - '@typescript-eslint'
extends:
  - semistandard
  - 'plugin:prettier/recommended'
  - 'plugin:@typescript-eslint/recommended'
globals:
  __DEV__: readonly
  __PROD__: readonly
rules:
  comma-dangle: [error, only-multiline]
  lines-between-class-members: off
  max-len:
    - error
    - code: 140
      ignoreComments: true
      ignoreUrls: true
      ignoreRegExpLiterals: true
      ignoreTemplateLiterals: true
  no-dupe-class-members: off
  no-tabs: off
  no-undef: off
  # using @typescript-eslint/no-useless-constructor instead
  no-useless-constructor: off
  no-use-before-define: off
  # using @typescript-eslint/semi instead
  semi: off
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
  spaced-comment:
    - error
    - always
    - markers: ['/']
      exceptions: ['/']
  standard/computed-property-even-spacing: off
  '@typescript-eslint/adjacent-overload-signatures': error
  '@typescript-eslint/array-type': [error, { default: 'array-simple' }]
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/indent': off
  '@typescript-eslint/interface-name-prefix': off
  '@typescript-eslint/member-delimiter-style': off
  '@typescript-eslint/member-ordering':
    - error
    - default:
        - public-static-field
        - private-static-field
        - public-instance-field
        - private-instance-field
        - public-constructor
        - private-constructor
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-inferrable-types': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/no-useless-constructor': error
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/semi': error
overrides:
  - files: ['build/**/*.js']
    env:
      node: true
    rules:
      '@typescript-eslint/no-var-requires': off
  - files: ['**/*.ts', '**/*.tsx']
    parser: '@typescript-eslint/parser'
  - files: ['src/common/**']
    parserOptions:
      project: ./src/common/tsconfig.json
  - files: ['src/main/**']
    parserOptions:
      project: ./src/main/tsconfig.json
  - files: ['src/worker/**']
    parserOptions:
      project: ./src/worker/tsconfig.json
  - files: ['src/worklet/**']
    parserOptions:
      project: ./src/worklet/tsconfig.json
